# Generated by Django 2.2.6 on 2019-11-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updatedd_at',
            new_name='updated_at',
        ),
    ]
