# Generated by Django 2.2.6 on 2019-11-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='open_date',
        ),
    ]
