# Generated by Django 2.2.6 on 2019-11-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='open_date',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
